"""
Report Generator Skill — مولّد التقارير
=========================================
Generate structured reports: property analysis, market reports,
performance summaries, and client reports.
"""

import json
import logging
from datetime import datetime
from pathlib import Path

logger = logging.getLogger("skills.report_generator")


class ReportGeneratorSkill:
    """Report generation skill."""

    def generate_property_report(self, property_data: dict) -> str:
        """Generate a comprehensive property report."""
        return f"""# Property Report

## Property Overview
- **Title:** {property_data.get('title', 'N/A')}
- **Location:** {property_data.get('location', 'N/A')}
- **Price:** {property_data.get('price', 'N/A')} EGP
- **Type:** {property_data.get('type', 'N/A')}
- **Area:** {property_data.get('area', 'N/A')} sqm
- **Bedrooms:** {property_data.get('bedrooms', 'N/A')}
- **Bathrooms:** {property_data.get('bathrooms', 'N/A')}

## Description
{property_data.get('description', 'No description available.')}

## Features
{self._list_to_markdown(property_data.get('features', []))}

## Market Analysis
- **Average price/sqm in area:** {property_data.get('avg_price_sqm', 'N/A')} EGP
- **Price vs market:** {property_data.get('price_vs_market', 'N/A')}
- **Demand level:** {property_data.get('demand_level', 'N/A')}

## Investment Potential
- **Rental yield estimate:** {property_data.get('rental_yield', 'N/A')}%
- **Appreciation outlook:** {property_data.get('appreciation_outlook', 'N/A')}
- **ROI score:** {property_data.get('roi_score', 'N/A')}/10

## Recommendation
{property_data.get('recommendation', 'Further analysis recommended.')}

---
*Generated by CityEstate on {datetime.now().strftime('%Y-%m-%d %H:%M')}*
"""

    def generate_market_report(self, market_data: dict) -> str:
        """Generate a market analysis report."""
        return f"""# Real Estate Market Report

## Market Overview
- **Area:** {market_data.get('area', 'N/A')}
- **Date:** {market_data.get('date', datetime.now().strftime('%Y-%m-%d'))}
- **Market condition:** {market_data.get('condition', 'N/A')}

## Price Trends
- **Average price:** {market_data.get('avg_price', 'N/A')} EGP
- **Price change (YoY):** {market_data.get('price_change_yoy', 'N/A')}%
- **Price trend:** {market_data.get('price_trend', 'N/A')}

## Supply & Demand
- **Active listings:** {market_data.get('active_listings', 'N/A')}
- **Days on market (avg):** {market_data.get('avg_days_on_market', 'N/A')}
- **Absorption rate:** {market_data.get('absorption_rate', 'N/A')}

## Popular Property Types
{self._dict_to_markdown(market_data.get('popular_types', {}))}

## Key Insights
{self._list_to_markdown(market_data.get('insights', []))}

## Outlook
{market_data.get('outlook', 'Market outlook pending further data.')}

---
*Generated by CityEstate on {datetime.now().strftime('%Y-%m-%d %H:%M')}*
"""

    def generate_client_report(self, client_data: dict) -> str:
        """Generate a client activity report."""
        return f"""# Client Report

## Client Information
- **Name:** {client_data.get('name', 'N/A')}
- **Contact:** {client_data.get('contact', 'N/A')}
- **Client since:** {client_data.get('since', 'N/A')}

## Requirements
- **Budget:** {client_data.get('budget', 'N/A')} EGP
- **Preferred areas:** {', '.join(client_data.get('areas', []))}
- **Property type:** {client_data.get('property_type', 'N/A')}
- **Bedrooms:** {client_data.get('bedrooms', 'N/A')}

## Activity Summary
- **Properties viewed:** {client_data.get('properties_viewed', 0)}
- **Proposals made:** {client_data.get('proposals', 0)}
- **Status:** {client_data.get('status', 'Active')}

## Matched Properties
{self._list_to_markdown(client_data.get('matched_properties', []))}

## Next Steps
{self._list_to_markdown(client_data.get('next_steps', []))}

---
*Generated by CityEstate on {datetime.now().strftime('%Y-%m-%d %H:%M')}*
"""

    def generate_performance_report(self, performance_data: dict) -> str:
        """Generate a performance/dashboard report."""
        return f"""# Performance Report

## Period: {performance_data.get('period', 'Last 30 days')}

## Key Metrics
| Metric | Value | Change |
|--------|-------|--------|
| Leads generated | {performance_data.get('leads', 0)} | {performance_data.get('leads_change', 'N/A')}% |
| Deals closed | {performance_data.get('deals', 0)} | {performance_data.get('deals_change', 'N/A')}% |
| Revenue | {performance_data.get('revenue', 0):,} EGP | {performance_data.get('revenue_change', 'N/A')}% |
| Client satisfaction | {performance_data.get('satisfaction', 'N/A')}/5 | {performance_data.get('satisfaction_change', 'N/A')} |

## Lead Sources
{self._dict_to_markdown(performance_data.get('lead_sources', {}))}

## Top Performing Areas
{self._list_to_markdown(performance_data.get('top_areas', []))}

## Goals Progress
{self._dict_to_markdown(performance_data.get('goals_progress', {}))}

## Recommendations
{self._list_to_markdown(performance_data.get('recommendations', []))}

---
*Generated by CityEstate on {datetime.now().strftime('%Y-%m-%d %H:%M')}*
"""

    def save_report(self, content: str, filename: str, report_type: str = "general") -> dict:
        """Save a report to file."""
        output_dir = Path(f"output/reports/{report_type}")
        output_dir.mkdir(parents=True, exist_ok=True)
        filepath = output_dir / filename
        filepath.write_text(content, encoding="utf-8")
        return {"status": "saved", "file": str(filepath), "type": report_type}

    def _list_to_markdown(self, items: list) -> str:
        if not items:
            return "- No data available"
        return "\n".join(f"- {item}" for item in items)

    def _dict_to_markdown(self, data: dict) -> str:
        if not data:
            return "- No data available"
        return "\n".join(f"- **{k}:** {v}" for k, v in data.items())


def get_report_tools():
    """Return CrewAI-compatible tools for report generation."""
    from crewai.tools import BaseTool
    from pydantic import BaseModel, Field

    class PropertyReportInput(BaseModel):
        title: str = Field(description="Property title")
        location: str = Field(default="N/A", description="Property location")
        price: str = Field(default="N/A", description="Property price")
        property_type: str = Field(default="N/A", description="Property type")
        area: str = Field(default="N/A", description="Area in sqm")
        bedrooms: str = Field(default="N/A", description="Number of bedrooms")

    class PropertyReportTool(BaseTool):
        name: str = "generate_property_report"
        description: str = "Generate a comprehensive property report with market analysis."
        args_schema: type = PropertyReportInput

        def _run(self, title: str, location: str = "N/A", price: str = "N/A", property_type: str = "N/A", area: str = "N/A", bedrooms: str = "N/A") -> str:
            skill = ReportGeneratorSkill()
            report = skill.generate_property_report({
                "title": title, "location": location, "price": price,
                "type": property_type, "area": area, "bedrooms": bedrooms,
            })
            result = skill.save_report(report, f"{title.replace(' ', '_')}.md", "property")
            return json.dumps({"report": report, "saved": result}, ensure_ascii=False)

    class MarketReportInput(BaseModel):
        area: str = Field(description="Market area")
        avg_price: str = Field(default="N/A", description="Average price")
        condition: str = Field(default="N/A", description="Market condition")

    class MarketReportTool(BaseTool):
        name: str = "generate_market_report"
        description: str = "Generate a market analysis report for an area."
        args_schema: type = MarketReportInput

        def _run(self, area: str, avg_price: str = "N/A", condition: str = "N/A") -> str:
            skill = ReportGeneratorSkill()
            report = skill.generate_market_report({"area": area, "avg_price": avg_price, "condition": condition})
            result = skill.save_report(report, f"market_{area.replace(' ', '_')}.md", "market")
            return json.dumps({"report": report, "saved": result}, ensure_ascii=False)

    return [PropertyReportTool(), MarketReportTool()]
