#!/usr/bin/env python3
"""
Secrets bootstrap — generate `.env` on first run.

Behavior:
  * If `.env` is missing: generate fresh secrets (JWT, Fernet key, salt, admin)
    and require the operator to paste in their `ROUTER_API_KEY` and
    `JINA_API_KEY` before the file is written. If those keys are present
    in the parent shell env, they are used; otherwise the operator is
    prompted.
  * If `.env` exists: print a warning and refuse to overwrite unless
    `--rotate` is passed.
  * `--rotate [KEY1,KEY2,...]`: rotate a subset of secrets. Always re-prompts
    for external provider keys.

This script never prints secret values to the terminal after generation.
The generated `.env` is `chmod 600` on POSIX systems; on Windows the
operator is told to mark the file as private.
"""

from __future__ import annotations

import argparse
import os
import secrets
import stat
import string
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
ENV_PATH = PROJECT_ROOT / ".env"
EXAMPLE_PATH = PROJECT_ROOT / ".env.example"

# Secrets generated locally. Never logged.
LOCAL_SECRETS = (
    "JWT_SECRET",
    "SESSION_VAULT_KEY",
    "PASSWORD_SALT",
    "ADMIN_PASSWORD",
    "EXTENSION_SHARED_SECRET",
)

# Secrets that must come from the operator (external providers).
EXTERNAL_SECRETS = (
    "ROUTER_API_KEY",
    "JINA_API_KEY",
)

# Non-secret settings that can default.
DEFAULTS = {
    "DATABASE_URL": "sqlite:///output/cityestate.db",
    "ROUTER_BASE_URL": "https://openrouter.ai/api/v1",
    "ROUTER_MODEL": "inclusionai/ling-3.0-flash:free",
    "ALLOWED_ORIGINS": "http://localhost:8050,http://localhost:3000",
    "API_VERSION": "v1",
    "ENVIRONMENT": "development",
    "LOG_LEVEL": "INFO",
}


def _gen_jwt_secret() -> str:
    return secrets.token_urlsafe(64)


def _gen_fernet_key() -> str:
    from cryptography.fernet import Fernet
    return Fernet.generate_key().decode("ascii")


def _gen_salt() -> str:
    return secrets.token_hex(32)


def _gen_admin_password() -> str:
    alphabet = string.ascii_letters + string.digits + "!@#$%^&*"
    while True:
        pw_chars = [
            secrets.choice(string.ascii_uppercase),
            secrets.choice(string.ascii_lowercase),
            secrets.choice(string.digits),
            secrets.choice("!@#$%^&*"),
        ]
        pw_chars += [secrets.choice(alphabet) for _ in range(12)]
        secrets.SystemRandom().shuffle(pw_chars)
        pw = "".join(pw_chars)
        if len(set(pw) & set("!@#$%^&*")) >= 1 and any(c.isdigit() for c in pw):
            return pw


def _gen_extension_secret() -> str:
    """>=32 chars url-safe random; satisfies FastAPI Field min_length=16."""
    return secrets.token_urlsafe(48)


GENERATORS = {
    "JWT_SECRET": _gen_jwt_secret,
    "SESSION_VAULT_KEY": _gen_fernet_key,
    "PASSWORD_SALT": _gen_salt,
    "ADMIN_PASSWORD": _gen_admin_password,
    "EXTENSION_SHARED_SECRET": _gen_extension_secret,
}


def _parse_existing(path: Path) -> dict[str, str]:
    out: dict[str, str] = {}
    if not path.exists():
        return out
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        if "=" not in line:
            continue
        k, _, v = line.partition("=")
        out[k.strip()] = v.strip()
    return out


def _prompt(label: str, *, required: bool, default: str | None = None, secret: bool = False) -> str | None:
    suffix = " [required]" if required else f" [{default}]" if default else ""
    while True:
        try:
            value = input(f"{label}{suffix}: ").strip()
        except EOFError:
            return default
        if not value:
            if default is not None:
                return default
            if not required:
                return None
            print(f"  {label} is required.")
            continue
        return value


def _build(rotate_keys: set[str]) -> dict[str, str]:
    """Build the new env dict."""
    env = _parse_existing(EXAMPLE_PATH) or {}
    existing = _parse_existing(ENV_PATH)

    for key in LOCAL_SECRETS:
        if key in rotate_keys or key not in existing:
            env[key] = GENERATORS[key]()

    for key in EXTERNAL_SECRETS:
        prior = os.environ.get(key) or existing.get(key)
        if key in rotate_keys or not prior or prior.startswith("<"):
            env[key] = _prompt(key, required=True, secret=True) or ""
        else:
            env[key] = prior

    for key, val in DEFAULTS.items():
        env.setdefault(key, val)

    return env


def _write(env: dict[str, str]) -> None:
    lines = [
        "# =============================================================================",
        "# CityEstate — generated by scripts/bootstrap_env.py on " + _now_iso(),
        "# DO NOT commit. DO NOT edit by hand. Run `python scripts/bootstrap_env.py --rotate` to regenerate.",
        "# =============================================================================",
        "",
    ]
    for key in list(LOCAL_SECRETS) + list(EXTERNAL_SECRETS) + list(DEFAULTS):
        if key in env:
            lines.append(f"{key}={env[key]}")
    lines.append("")
    ENV_PATH.write_text("\n".join(lines), encoding="utf-8")
    try:
        ENV_PATH.chmod(stat.S_IRUSR | stat.S_IWUSR)
    except (OSError, NotImplementedError):
        pass


def _now_iso() -> str:
    from datetime import datetime, timezone
    return datetime.now(timezone.utc).isoformat()


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate or rotate CityEstate secrets.")
    parser.add_argument("--rotate", nargs="*", default=None,
                        help="Rotate specified keys (or all if no args given).")
    args = parser.parse_args()

    if not EXAMPLE_PATH.exists():
        print(f"ERROR: missing {EXAMPLE_PATH}", file=sys.stderr)
        return 2

    if ENV_PATH.exists() and not args.rotate:
        print(f".env already exists at {ENV_PATH}.")
        print("Refusing to overwrite. Pass --rotate [KEY ...] to regenerate.")
        print("Example: python scripts/bootstrap_env.py --rotate")
        return 1

    rotate_keys: set[str] = set()
    if args.rotate is not None:
        rotate_keys = set(args.rotate) if args.rotate else set(LOCAL_SECRETS)
        for k in rotate_keys:
            if k not in LOCAL_SECRETS + EXTERNAL_SECRETS:
                print(f"WARNING: unknown key {k} — ignoring.")

    env = _build(rotate_keys)
    _write(env)
    print(f"Wrote {ENV_PATH} with {len(env)} variables.")
    print()
    print("Next steps:")
    print("  1. Verify file permissions: only the service account should read it.")
    print("  2. Restart the API server so the new secrets take effect.")
    print("  3. If this was a rotation, invalidate any active JWTs and reissue.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
